name: Client CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: irehankhan/random-textfile-client:1.0

      - name: Send Email Notification
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.EMAIL_PASSWORD }}
        run: |
            python - <<EOF
            import smtplib
            from email.mime.text import MIMEText
  
            sender_email = "irehankhan@yahoo.com"
            receiver_email = "irehankhan@yahoo.com"
            subject = "GitHub Action Notification"
            body = "The GitHub Action workflow has been triggered on the main branch."
  
            msg = MIMEText(body)
            msg["Subject"] = subject
            msg["From"] = sender_email
            msg["To"] = receiver_email
  
            with smtplib.SMTP("smtp.mail.yahoo.com", 587) as server:
                server.starttls()
                server.login(sender_email, ${{ secrets.EMAIL_PASSWORD }})
                server.sendmail(sender_email, [receiver_email], msg.as_string())
            EOF